import { Inter } from "next/font/google";
import "./globals.css";
import Exclude_signup_login from "@/components/Exclude_signup_login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Exclude_signup_login />
                {children}
            </body>
        </html>
    );
}
